# DEBUG = True
DEBUG = False

NUM_EPISODES = 1000
ENV_NAME='CartPole-v1'

# Hyperparameters
BATCH_SIZE = 64
MEMORY_SIZE = BATCH_SIZE * BATCH_SIZE
EPSILON_START = 0.9
EPSILON_END = 0.05
if DEBUG:
    EPSILON_START = 0
    EPSILON_END = 0
EPSILON_DECAY = 500

GAMMA = 0.99
LR = 1e-4

TAU = 0.005
NN_WIDTH = 128
NN_DEPTH = 3
