# DEBUG = True
DEBUG = False

NUM_EPISODES = 1200
# ENV_NAME='CartPole-v1'
ENV_NAME='MountainCar-v0'

# Hyperparameters
BATCH_SIZE = 256
MEMORY_SIZE = BATCH_SIZE * BATCH_SIZE
EPSILON_START = 1.00
EPSILON_END = 0.005
if DEBUG:
    EPSILON_START = EPSILON_END
EPSILON_DECAY = 500

GAMMA = 0.99
LR = 1e-4

TAU = 0.005
NN_WIDTH = 128
NN_DEPTH = 3

isResNet = False
